package fr.ca.sa.commons.constants;

/**
 * 
 * Constants used in Error handling process
 * 
 * @author Sasa Radovanovic
 *
 */
public final class ErrorConstants {

	private ErrorConstants() {
		throw new IllegalAccessError("Utility class");
	}

	// Msg to be thrown with Exception for trying to access resource without
	// proper permission
	public static final String ERROR_MSG_ACCESS_RIGHT = "NCT_ERROR_ACCESS_RIGHT_FAILURE";
	public static final String ERROR_MSG_USER_NOT_ACTIVE = "NCT_ERROR_USER_NOT_ACTIVE";

	public static final String ERROR_MSG_DB_CONNECTION = "NCT_ERROR_DATABASE_CONNECTION";

	public static final String ERROR_MSG_GET_USER_INFO = "NCT_ERROR_UNKNOWN_USER";
	public static final String ERROR_MSG_GET_TODO_LIST = "NCT_ERROR_GET_USER_TODO_LIST";
	public static final String ERROR_MSG_INSERT_TODO_ITEM = "NCT_ERROR_INSERT_TODO_ITEM";
	public static final String ERROR_MSG_DELETE_TODO_ITEM = "NCT_ERROR_DELETE_TODO_ITEM";
	public static final String ERROR_MSG_UPDATE_TODO_ITEM = "NCT_ERROR_UPDATE_TODO_ITEM";
	
	public static final String ERROR_MSG_APP_VERSION = "NCT_ERROR_APP_VERSION";

	public static final String ERROR_MSG_GET_USER_DATA = "NCT_ERROR_GET_USER_DATA";

	public static final String ERROR_MSG_GET_USER_MESSAGES_AND_ALERTS = "NCT_ERROR_GET_USER_MESSAGES_AND_ALERTS";
	public static final String ERROR_MSG_DELETE_USER_MESSAGES = "ERROR_MSG_DELETE_USER_MESSAGES";

	public static final String ERROR_MSG_UPDATE_AGENDA_ITEM = "NCT_ERROR_MSG_UPDATE_AGENDA_ITEM";
	public static final String ERROR_MSG_CANCEL_AGENDA_ITEM = "NCT_ERROR_MSG_CANCEL_AGENDA_ITEM";
	public static final String ERROR_MSG_GET_AGENDA_INFO = "NCT_ERROR_MSG_GET_AGENDA_INFO";
	public static final String ERROR_MSG_CANCEL_AGENDA_ADD_PARTICIPANT = "NCT_ERROR_MSG_AGENDA_ADD_PARTICIPANT";
	public static final String ERROR_MSG_GET_NOT_CLOSED_AGENDA_COUNT = "NCT_ERROR_MSG_GET_NOT_CLOSED_AGENDA_COUNT";

	public static final String ERROR_MSG_GET_CLIENT_INFO = "NCT_ERROR_GET_CLIENT_INFO";

	public static final String ERROR_NCT_AGENDA_BLOCKING_EXISTS = "NCT_AGENDA_BLOCKING_EXISTS";
	public static final String ERROR_NCT_AGENDA_ELEMENT_ID_WRONG_VALUE = "NCT_AGENDA_ELEMENT_ID_WRONG_VALUE";
	public static final String ERROR_NCT_AGENDA_NONWORKING_DAY = "ERROR_NCT_AGENDA_NONWORKING_DAY";
	public static final String ERROR_NCT_AGENDA_INVALID_TIME_INTERVAL = "ERROR_NCT_AGENDA_INVALID_TIME_INTERVAL";
	
	public static final String ERROR_PERMISSION_MATRIX_LOAD = "NCT_ERROR_PERMISSION_MATRIX_LOAD";

	public static final String ERROR_MSG_LOAD_OPPORTUNITIES_TREATED_REASONS = "NCT_ERROR_LOAD_OPPORTUNITIES_TREATED_REASONS";
	public static final String ERROR_MSG_SET_OPPORTUNITIES_TREATED_REASONS = "NCT_ERROR_SET_OPPORTUNITIES_TREATED_REASONS";

	public static final String ERROR_MSG_LOAD_OPPORTUNITIES = "NCT_ERROR_LOAD_OPPORTUNITIES";
	public static final String ERROR_MSG_REASSIGN_OPPORTUNITY = "NCT_ERROR_REASSIGN_OPPORTUNITY";
	public static final String ERROR_MSG_CANCEL_OPPORTUNITY = "NCT_ERROR_CANCEL_OPPORTUNITY";

	public static final String ERROR_MSG_GET_QCR_CONFIGURATION = "NCT_ERROR_GET_QCR_CONFIGURATION";
	public static final String ERROR_MSG_GET_QCR_DETAILS = "NCT_ERROR_GET_QCR_DETAILS";
	public static final String ERROR_MSG_CREATE_QCR = "NCT_ERROR_CREATE_QCR";
	public static final String ERROR_MSG_UPDATE_QCR = "NCT_ERROR_UPDATE_QCR";

	public static final String ERROR_MSG_SET_PROSPECT = "NCT_ERROR_SET_PROSPECT";
	public static final String ERROR_MSG_GET_PROSPECT_DATA = "NCT_ERROR_GET_PROSPECT_DATA";
	public static final String ERROR_MSG_PROSPECT_DUPLICATE = "NCT_ERROR_PROSPECT_DUPLICATE";

	public static final String ERROR_MSG_LOAD_PORTFOLIOS = "NCT_ERROR_LOAD_PORTFOLIOS";
	public static final String ERROR_MSG_LOAD_PORTFOLIO_CLIENT_BY_SEGEMENT = "NCT_ERROR_LOAD_PORTFOLIO_CLIENT_BY_SEGEMENT";
	public static final String ERROR_MSG_REASSIGN_PORTFOLIOS = "NCT_ERROR_REASSIGN_PORTFOLIOS";

	public static final String ERROR_MSG_LOAD_PRODUCTS = "NCT_ERROR_LOAD_PRODUCTS";

	public static final String ERROR_MSG_LOAD_PROJECTS = "NCT_ERROR_LOAD_PROJECTS";
	public static final String ERROR_MSG_CANCEL_PROJECT = "NCT_ERROR_CANCEL_PROJECT";

	public static final String ERROR_MSG_SAVE_BASKET = "NCT_ERROR_SAVE_BASKET";
	public static final String ERROR_MSG_LOAD_BASKET = "NCT_ERROR_LOAD_BASKET";

	public static final String ERROR_MSG_LOAD_NEEDS = "NCT_ERROR_LOAD_NEEDS";

	public static final String ERROR_MSG_AGREED_OFFER_STATUSES = "NCT_ERROR_LOAD_AGREED_OFFER_STATUSES";
	public static final String ERROR_MSG_AGREED_OFFER_TYPES = "NCT_ERROR_LOAD_AGREED_OFFER_TYPES";

	public static final String ERROR_MSG_LOAD_OPP_STATUSES = "ERROR_MSG_LOAD_OPP_STATUSES";

	public static final String ERROR_MSG_LOAD_STATISTICS = "NCT_ERROR_LOAD_STATISTICS";
	public static final String ERROR_MSG_LOAD_STATISTICS_LIST = "NCT_ERROR_LOAD_STATISTICS_LIST";

	public static final String ERROR_MSG_LANGUAGE_NOT_FOUND = "NCT_ERROR_LANGUAGE_NOT_FOUND";
	public static final String ERROR_MSG_INVALID_TRANSLATIONS_FORMAT = "NCT_ERROR_MALFORMATED_TRANSLATIONS";
	public static final String ERROR_MSG_FILE_WRITE_ERROR = "NCT_ERROR_CANNOT_WRITE_FILE";

	public static final String ERROR_MSG_LOAD_CONTACT_HISTORY_DETAILS = "NCT_ERROR_LOAD_CONTACT_HISTORY_DETAILS";

	public static final String WSDL_ERR_HANDLING_DATA = "NCT_ERROR_WSDL_ERR_HANDLING_DATA";
	public static final String WSDL_ERR_EMPTY_RESPONSE = "NCT_ERROR_WSDL_ERR_EMPTY_RESPONSE";
	public static final String WSDL_ERR_CRITICAL_ERROR = "NCT_ERROR_WSDL_ERR_CRITICAL_ERROR";

	public static final String ERROR_MSG_USER_UNKOWN_POSITION= "NCT_ERROR_UNKNOWN_USER_POSITION";

	public static final String ERROR_MSG_GET_ADVISOR_ENTITY = "NCT_ERROR_MSG_GET_ADVISOR_ENTITY";
	public static final String ERROR_MSG_GET_AGENDA_PURPOSE = "NCT_ERROR_MSG_GET_AGENDA_PURPOSE";

	public static final String ERROR_MSG_LOAD_OPPORTUNITIES_DETAILS = "NCT_ERROR_LOAD_OPPORTUNITIES_DETAILS";
	public static final String ERROR_MSG_TREAT_OPPORTUNITY = "NCT_ERROR_TREAT_OPPORTUNITY";
	
	public static final String ERROR_MSG_WEB_SOCKET_SESSION_NOT_FOUND = "NCT_ERROR_WEB_SOCKET_SESSION_NOT_FOUND";
	public static final String ERROR_MSG_WEB_SOCKET_SESSION_NOT_OPENED = "NCT_ERROR_WEB_SOCKET_SESSION_NOT_OPENED";
	
	public static final String ERROR_MSG_SYNC_TOKEN_NOT_FOUND = "NCT_ERROR_SYNC_TOKEN_NOT_FOUND";
	/**
	 * 
	 * Management error messages
	 */
	public static final String ERROR_MSG_SET_JOB_DAILY_SCHEDULE = "NCT_ERROR_SET_JOB_DAILY_SCHEDULE";
	public static final String ERROR_MSG_SET_JOB_FLOWS = "NCT_ERROR_SET_JOB_FLOWS";
	public static final String ERROR_MSG_GET_JOB_EXECUTIONS_BY_DATE = "NCT_ERROR_GET_JOB_EXECUTION_BY_DATE";
	public static final String ERROR_MSG_GET_CONFIGURATION_PARAMETERS = "NCT_ERROR_GET_CONFIGURATION_PARAMETERS";
	public static final String ERROR_MSG_SET_CONFIGURATION_PARAMETERS = "NCT_ERROR_SET_CONFIGURATION_PARAMETERS";
	
	public static final String ERROR_MSG_GET_CAMPAIGNS = "NCT_ERROR_GET_CAMPAIGNS";
	public static final String ERROR_MSG_SET_CAMPAIGNS = "NCT_ERROR_SET_CAMPAIGNS";

	public static final String ERROR_MSG_SET_WORKING_HOURS = "NCT_ERROR_SET_WORKING_HOURS";
	public static final String ERROR_MSG_GET_WORKING_HOURS = "NCT_ERROR_GET_WORKING_HOURS";

	public static final String ERROR_MSG_SET_ROLE = "NCT_ERROR_SET_ROLE";
	public static final String ERROR_MSG_SET_ROLE_DETAILS = "NCT_ERROR_SET_ROLE_DETAILS";
	public static final String ERROR_MSG_SET_COLLABORATOR_ROLE = "NCT_ERROR_SET_COLLABORATOR_ROLE";
	public static final String ERROR_MSG_SET_FUNCTION_ROLE = "NCT_ERROR_SET_FUNCTION_ROLE";
	public static final String ERROR_MSG_GET_ROLES = "NCT_ERROR_GET_ROLES";
	public static final String ERROR_MSG_GET_COLLABORATOR_ROLES = "NCT_ERROR_GET_COLLABORATOR_ROLES";
	public static final String ERROR_MSG_GET_ROLE_PERIMETER = "NCT_ERROR_GET_ROLE_PERIMETER";
	public static final String ERROR_MSG_GET_ROLE_OBJECT_LEVELS = "NCT_ERROR_GET_ROLE_OBJECT_LEVELS";
	public static final String ERROR_MSG_GET_ROLE_ADMIN_LEVELS = "NCT_ERROR_GET_ROLE_ADMIN_LEVELS";
	public static final String ERROR_MSG_DELETE_ROLE = "NCT_ERROR_DELETE_ROLE";

	public static final String ERROR_MSG_SET_NON_WORKING_DAYS = "NCT_ERROR_SET_NON_WORKING_DAYS";
	public static final String ERROR_MSG_GET_NON_WORKING_DAYS = "NCT_ERROR_GET_NON_WORKING_DAYS";

	public static final String ERROR_MSG_GET_JOB_DAILY_SCHEDULE = "NCT_ERROR_GET_JOB_DAILY_SCHEDULE";
	public static final String ERROR_MSG_SET_JOB = "NCT_ERROR_SET_JOB";
	public static final String ERROR_MSG_DELETE_JOB = "NCT_ERROR_DELETE_JOB";
	public static final String ERROR_MSG_DELETE_JOB_FLOWS = "NCT_ERROR_DELETE_JOB_FLOWS";
	public static final String ERROR_MSG_GET_FLOW_EXECUTIONS_BY_JOB_ID = "NCT_ERROR_GET_FLOW_EXECUTIONS_BY_JOB_ID";
	public static final String ERROR_MSG_GET_FLOW_CONFIGURATION = "NCT_ERROR_GET_FLOW_CONFIGURATION";

	public static final String ERROR_MSG_SET_BANK_PARAMETERS = "NCT_ERROR_SET_BANK_PARAMETERS";

	public static final String ERROR_MSG_GET_BANK_LANGUAGES = "NCT_ERROR_GET_BANK_LANGUAGES";
	public static final String ERROR_MSG_SET_BANK_LANGUAGES = "NCT_ERROR_SET_BANK_LANGUAGES";

	public static final String ERROR_MSG_GET_BANK_LANGUAGE_PARAMETERS = "NCT_ERROR_GET_BANK_LANG_PARAMETERS";
	public static final String ERROR_MSG_SET_BANK_LANGUAGE_PARAMETERS = "NCT_ERROR_SET_BANK_LANG_PARAMETERS";

	public static final String ERROR_MSG_SET_HOMEPAGE_LINKS = "NCT_ERROR_SET_HOMEPAGE_LINKS";
	public static final String ERROR_MSG_GET_HOMEPAGE_LINKS = "NCT_ERROR_GET_HOMEPAGE_LINKS";

	public static final String ERROR_MSG_SET_CODE_TABLE_DATA = "NCT_ERROR_SET_CODE_TABLE_DATA";
	public static final String ERROR_MSG_GET_CODE_TABLE_DATA = "NCT_ERROR_GET_CODE_TABLE_DATA";
	public static final String ERROR_MSG_GET_CODE_TABLE_CONFIG = "NCT_ERROR_GET_CODE_TABLE_CONFIG";

	public static final String ERROR_MSG_GET_OPPORTUNITY_CATEGORY = "NCT_ERROR_GET_OPPORTUNITY_CATEGORY";
	public static final String ERROR_MSG_GET_OPPORTUNITY_SUB_CATEGORY = "NCT_ERROR_GET_OPPORTUNITY_SUB_CATEGORY";
	
	/**
	 * 
	 * Agenda API error messages
	 */
	public static final String ERROR_MSG_GET_AGENDA_ELEMENT = "NCT_ERROR_MSG_GET_AGENDA_ELEMENT";
	
	// Default Error properties (Default Error will be sent if unknown exception
	// occurs)
	public static final int DEFAULT_ERROR_HTTP_CODE = 500;
	public static final int BAD_REQUEST_CODE = 400;
	public static final int DEFAULT_ERROR_ERROR_CODE = 11;
	public static final int DEFAULT_ERROR_SEVERITY = 0;
	public static final String DEFAULT_ERROR_MSG = "NCT_ERROR_CRITICAL_SERVER";

	// Token not verified (expired, invalid or not issued by NCT)
	public static final int INVALID_TOKEN = -100;
	public static final String ERROR_MSG_LOAD_PORTFOLIO_FILTER = "ERROR_MSG_LOAD_PORTFOLIO_FILTER";
		
	// code audit CWE 209 fixes
	public static final String ERROR_MSG_TRANSLATED_LANGUAGE_IO_EXCEPTION = "ERROR_MSG_TRANSLATED_LANGUAGE_IO_EXCEPTION";	
	public static final String ERROR_MSG_JMS_MESSAGE_PARSER_PARSE_INPUT_STREAM = "ERROR_MSG_JMS_MESSAGE_PARSER_PARSE_INPUT_STREAM";
	public static final String ERROR_MSG_FAILED_SQL_STATEMENT = "ERROR_MSG_FAILED_SQL_STATEMENT";
	public static final String ERROR_MSG_FAILED_TO_LOOKUP_DATASOURCE = "ERROR_MSG_FAILED_TO_LOOKUP_DATASOURCE";
	public static final String ERROR_MSG_IMAGE_HANDLING_EXCEPTION = "ERROR_MSG_IMAGE_HANDLING_EXCEPTION";
}
