
package fr.ca.sa.externalClients.wsdl.leadserviceV2.leadservice.nct;



import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService_NCTLeadSoap", targetNamespace = "http://NCT.leadservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceNCTLeadSoap {


    /**
     * 
     * @param part
     * @return
     *     returns leadservice.nct.FLOWLEAOUTResponse
     */
    @WebMethod(operationName = "Lead", action = "http://NCT.leadservice/WebService_NCTLead/Lead")
    @WebResult(name = "FLOW_LEA_OUT_Response", targetNamespace = "http://NCT.leadservice", partName = "LeadResult")
    public FLOWLEAOUTResponse lead(
        @WebParam(name = "FLOW_LEA_OUT_Request", targetNamespace = "http://NCT.leadservice", partName = "part")
        FLOWLEAOUTRequest part);

}
