
package fr.ca.sa.externalClients.wsdl.leadservice.nct;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LeaOutPort", targetNamespace = "http://NCT.leadservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LeaOutPort {


    /**
     * 
     * @param flowLEAOUTRequest
     * @return
     *     returns leadservice.nct.FLOWLEAOUTResponse
     */
    @WebMethod(operationName = "FLOW_LEA_OUT_")
    @WebResult(name = "FLOW_LEA_OUT_Response", targetNamespace = "http://NCT.leadservice", partName = "FLOW_LEA_OUT_Response")
    public FLOWLEAOUTResponse flowLEAOUT(
        @WebParam(name = "FLOW_LEA_OUT_Request", targetNamespace = "http://NCT.leadservice", partName = "FLOW_LEA_OUT_Request")
        FLOWLEAOUTRequest flowLEAOUTRequest);

}
