
package fr.ca.sa.externalClients.wsdl.leadservice.nct;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.jboss.logging.Logger;

import fr.ca.sa.nct.commons.NCTSystemConstants;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LeaOutPortService", targetNamespace = "http://NCT.leadservice")
public class LeaOutPortService
    extends Service
{
	private static final Logger LOGGER = Logger.getLogger(LeaOutPortService.class);

	private static final URL LEAOUTPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException LEAOUTPORTSERVICE_EXCEPTION;
    private static final QName LEAOUTPORTSERVICE_QNAME = new QName("http://NCT.leadservice", "LeaOutPortService");

    static {
        URL url = null;
        WebServiceException exc = null;
        try {
             url = new URL(NCTSystemConstants.getWsdlAddressLead());
        } catch (MalformedURLException ex) {
            exc = new WebServiceException(ex);
            LOGGER.error("=================================================");
            LOGGER.error("Problem during setup WSDL URL for lead service",ex);
            LOGGER.error("=================================================");
        }
        LEAOUTPORTSERVICE_WSDL_LOCATION = url;
        LEAOUTPORTSERVICE_EXCEPTION = exc;
    }

    public LeaOutPortService() {
        super(__getWsdlLocation(), LEAOUTPORTSERVICE_QNAME);
    }

    public LeaOutPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEAOUTPORTSERVICE_QNAME, features);
    }

    public LeaOutPortService(URL wsdlLocation) {
        super(wsdlLocation, LEAOUTPORTSERVICE_QNAME);
    }

    public LeaOutPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEAOUTPORTSERVICE_QNAME, features);
    }

    public LeaOutPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LeaOutPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LeaOutPort
     */
    @WebEndpoint(name = "LeaOutPortServicesoaphttp")
    public LeaOutPort getLeaOutPortServicesoaphttp() {
        return super.getPort(new QName("http://NCT.leadservice", "LeaOutPortServicesoaphttp"), LeaOutPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeaOutPort
     */
    @WebEndpoint(name = "LeaOutPortServicesoaphttp")
    public LeaOutPort getLeaOutPortServicesoaphttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://NCT.leadservice", "LeaOutPortServicesoaphttp"), LeaOutPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEAOUTPORTSERVICE_EXCEPTION!= null) {
            throw LEAOUTPORTSERVICE_EXCEPTION;
        }
        return LEAOUTPORTSERVICE_WSDL_LOCATION;
    }

}
