
package fr.ca.sa.externalClients.wsdl.leadservice.nct;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import fr.ca.sa.nct.commons.NCTSystemConstants;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "nct.adapter.ws.pub.NCTAdapter_LeadCreation", targetNamespace = "http://NCT.leadservice")
public class NctAdapterWsPubNCTAdapterLeadCreation
    extends Service
{


    private static final URL LEAOUTPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException LEAOUTPORTSERVICE_EXCEPTION;
    private static final QName LEAOUTPORTSERVICE_QNAME = new QName("http://NCT.leadservice", "nct.adapter.ws.pub.NCTAdapter_LeadCreation");
    static {
        URL url = null;
        WebServiceException exc = null;
        try {
             url = new URL(NCTSystemConstants.getWsdlAddressLead());
        } catch (MalformedURLException ex) {
            exc = new WebServiceException(ex);
        }
        LEAOUTPORTSERVICE_WSDL_LOCATION = url;
        LEAOUTPORTSERVICE_EXCEPTION = exc;
    }

    /**
     * default constructor for Lea Out Port Service
     */
    public NctAdapterWsPubNCTAdapterLeadCreation() {
        super(__getWsdlLocation(), LEAOUTPORTSERVICE_QNAME);
    }

    /**
     * Lea Out Port Service
     * 
     * @param features
     * 			Web service features
     */
    public NctAdapterWsPubNCTAdapterLeadCreation(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEAOUTPORTSERVICE_QNAME, features);
    }

    /**
     * Lea Out Port Service
     * 
     * @param wsdlLocation
     * 			URL for wsdl
     */
    public NctAdapterWsPubNCTAdapterLeadCreation(URL wsdlLocation) {
        super(wsdlLocation, LEAOUTPORTSERVICE_QNAME);
    }

    /**
     * Lea Out Port Service
     * 
     * @param wsdlLocation
     * 			URL for wsdl
     * 
     * @param features
     * 			Web service features
     */
    public NctAdapterWsPubNCTAdapterLeadCreation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEAOUTPORTSERVICE_QNAME, features);
    }

    /**
     * Lea Out Port Service
     * 
     * @param wsdlLocation
     * 			URL for wsdl
     * 
     * @param serviceName
     * 			Service name
     */
    public NctAdapterWsPubNCTAdapterLeadCreation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Lea Out Port Service
     * 
     * @param wsdlLocation
     * 			URL for wsdl
     * 
     * @param serviceName
     * 			Service name
     * 
     * @param features
     * 			Web service features
     */
    public NctAdapterWsPubNCTAdapterLeadCreation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LeaOutPort
     */
    @WebEndpoint(name = "LeaOutPortSoap11")
    public LeaOutPort getLeaOutPortSoap11() {
        return super.getPort(new QName("http://NCT.leadservice", "LeaOutPortSoap11"), LeaOutPort.class);
    }


    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeaOutPort
     */
    @WebEndpoint(name = "LeaOutPortSoap11")
    public LeaOutPort getLeaOutPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://NCT.leadservice", "LeaOutPortSoap11"), LeaOutPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEAOUTPORTSERVICE_EXCEPTION!= null) {
            throw LEAOUTPORTSERVICE_EXCEPTION;
        }
        return LEAOUTPORTSERVICE_WSDL_LOCATION;
    }

}
